access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://sudharsan151:ZGwlUCgYVRKOGkdQ@cluster0.1njxqg6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ${MONGODB_DB}
logging:
  level:
    org.springframework.security: DEBUG
